# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            echo export PATH="$HOME/.pyenv/bin:$PATH" >> ~/.bashrc
            echo eval "$(pyenv init -)" >> ~/.bashrc
            echo eval "$(pyenv virtualenv-init -)" >> ~/.bashrc
            cat ~/.bashrc
            virtualenv -p python3 .venv
            source .venv/bin/activate
            pip install --upgrade pip --user
            pip --version
            pip install pipenv
            pipenv install --dev
      - save_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        paths:
          - ".venv"
          - "/usr/local/bin"
          - "/usr/local/lib/python3.6/site-packages"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
