# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo chmod 777 -R /usr/local/lib/python3.6/site-packages/
            sudo pip install virtualenv
            virtualenv -p python3 .venv
            . .venv/bin/activate
            pip install --upgrade pip
            pip --version
            pip install pipenv
            pipenv install --dev
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: check pep8
          command: |
            . .venv/bin/activate
            pip install pep8
            pep8 gamelib

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
